
services:
  mysql:
    container_name: mysql
    image: arm64v8/mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin 'zcat /usr/share/doc/zabbix-server-mysql-7.0/create.sql.gz | mysql zabbix -uzabbix -pzxc*963'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rD
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zxc*963
      MYSQL_DATABASE: zabbix
    secrets:
      - db_root_password
      - db_password
    ports:
      - 3306:3306
    networks:
      - zabbix-network
  
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zxc*963
    secrets:
      - db_root_password
      - db_password
    ports:
      - 10050:10050
      - 10051:10051
    networks:
      - zabbix-network
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zxc*963
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - 80:8080
      - 443:8443
    secrets:
      - db_root_password
      - db_password
    networks:
      - zabbix-network
    depends_on:
      - mysql
      - zabbix-server

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

networks:
  zabbix-network:
    driver: bridge