
version: '3.5'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="P@ssw0rD"
      - MYSQL_USER:"zabbix"
      - MYSQL_PASSWORD:"zxc*963"
    secrets:
      - db_root_password
      - db_password
    ports:
      - 3306:3306
    networks:
      - zabbix-network
  
  zabbix-server:
    container_name: zabbix
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zxc*963
    secrets:
      - db_root_password
      - db_password
    ports:
      - 10050:10050
      - 10051:10051
    networks:
      - zabbix-network
    depends_on:
      - db

  zabbix-frontend:
    container_name: zabix-nginx
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zxc*963
      - ZBX_SERVER_HOST=zabbix
      - PHP_TZ:=America/Sao_Paulo
    secrets:
      - db_root_password
      - db_password
    ports:
      - 80:8080
      - 443:8443
    networks:
      - zabbix-network
    depends_on:
      - db
      - zabbix-server

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

networks:
  zabbix-network:
    driver: bridge