
version: '3.5'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_USER=zabbix_db_admin
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    ports:
      - 3306:3306
    networks:
      - zabbix-network
  
  zabbix-server:
    container_name: zabbix
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=zabbix_db_admin
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    ports:
      - 10050:10050
      - 10051:10051
    networks:
      - zabbix-network
    depends_on:
      - db

  zabbix-frontend:
    container_name: zabix-nginx
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=mariadb
      - MYSQL_USER=zabbix_db_admin
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - ZBX_SERVER_HOST=zabbix
      - PHP_TZ:=America/Sao_Paulo
    secrets:
      - db_root_password
      - db_password
    ports:
      - 80:8080
      - 443:8443
    networks:
      - zabbix-network
    depends_on:
      - db
      - zabbix-server

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

networks:
  zabbix-network:
    driver: bridge